package com.example.zuoye2.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.zuoye2.bean.Bean_Three;

import com.example.zuoye2.dao.Bean_ThreeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bean_ThreeDaoConfig;

    private final Bean_ThreeDao bean_ThreeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bean_ThreeDaoConfig = daoConfigMap.get(Bean_ThreeDao.class).clone();
        bean_ThreeDaoConfig.initIdentityScope(type);

        bean_ThreeDao = new Bean_ThreeDao(bean_ThreeDaoConfig, this);

        registerDao(Bean_Three.class, bean_ThreeDao);
    }
    
    public void clear() {
        bean_ThreeDaoConfig.clearIdentityScope();
    }

    public Bean_ThreeDao getBean_ThreeDao() {
        return bean_ThreeDao;
    }

}
